"""Initial Schema

Revision ID: 1feadf0954a0
Revises: 
Create Date: 2026-09-14 18:06:36.369979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1feadf0954a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('relative_humidity_pct', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_timestamp'), 'observations', ['timestamp'], unique=False)
    op.create_table('sensor_health',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('maintenance_required', sa.Integer(), nullable=True),
    sa.Column('predicted_failure_risk', sa.Float(), nullable=True),
    sa.Column('health_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_health_timestamp'), 'sensor_health', ['timestamp'], unique=False)
    op.create_table('anomaly_predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('observation_id', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('is_anomaly', sa.Integer(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_predictions')
    op.drop_index(op.f('ix_sensor_health_timestamp'), table_name='sensor_health')
    op.drop_table('sensor_health')
    op.drop_index(op.f('ix_observations_timestamp'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
