"""Add spatial_score to AnomalyPrediction

Revision ID: 259121f48a80
Revises: 7be6709b15aa
Create Date: 2026-09-15 00:35:49.052227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259121f48a80'
down_revision: Union[str, Sequence[str], None] = '7be6709b15aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_predictions', sa.Column('spatial_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_predictions', 'spatial_score')
    # ### end Alembic commands ###
