"""Add rich alert fields

Revision ID: 7be6709b15aa
Revises: 1feadf0954a0
Create Date: 2026-09-14 23:51:56.185068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be6709b15aa'
down_revision: Union[str, Sequence[str], None] = '1feadf0954a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('parameter', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('anomaly_type', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('anomaly_score', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('sensor_health', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('recommended_action', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('alerts', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('message', sa.VARCHAR(), nullable=True))
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'recommended_action')
    op.drop_column('alerts', 'description')
    op.drop_column('alerts', 'sensor_health')
    op.drop_column('alerts', 'anomaly_score')
    op.drop_column('alerts', 'anomaly_type')
    op.drop_column('alerts', 'parameter')
    # ### end Alembic commands ###
