"""Add confidence_pct

Revision ID: d95ad6a4a840
Revises: 259121f48a80
Create Date: 2026-09-15 01:05:03.749852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95ad6a4a840'
down_revision: Union[str, Sequence[str], None] = '259121f48a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('confidence_pct', sa.Float(), nullable=True))
    op.add_column('anomaly_predictions', sa.Column('confidence_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anomaly_predictions', 'confidence_pct')
    op.drop_column('alerts', 'confidence_pct')
    # ### end Alembic commands ###
